name: causal

dependencies:
    - python==3.6.6
    - pip:
        - numpy==1.16.0
        - gym==0.10.9
        - matplotlib==3.1.1
        - opencv-python
        - ray==0.8.2
        - tensorflow==2.0.0
        - scipy==1.2.0
        - setproctitleconda in
        - psutil
        - lz4
        - boto3==1.4.8
        - redis==3.3.2
        - pytz

